/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConnectingFrame.java
 *
 * Created on 2010-11-11, 19:01:07
 */

package eboard.view;

import javax.swing.JOptionPane;

/**
 *
 * @author elf
 */
public class ConnectingFrame extends javax.swing.JDialog {
    private static ConnectingFrame cf = null;
    /** Creates new form ConnectingFrame */
    private ConnectingFrame() {

        initComponents();
    }
    public static ConnectingFrame getInstance(){
        if(cf == null) cf = new ConnectingFrame();
        return cf;
    }

    public void popout(final String roomId,final int x, final int y){
         new Thread(new Runnable(){
            public void run(){
                setTitle("Connecting infomation:");
                jlbRoomId.setText(roomId);
                setLocation(x, y);
                repaint();
                setVisible(true);

                System.out.println(123);
            }
        }).start();
        

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlbRoomId = new javax.swing.JLabel();

        setResizable(false);

        jLabel1.setFont(new java.awt.Font("宋体", 0, 14));
        jLabel1.setText("Please wait when connecting to the room:");

        jlbRoomId.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jlbRoomId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jlbRoomId, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbRoomId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new ConnectingFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlbRoomId;
    // End of variables declaration//GEN-END:variables

}
