package eboard.view;


import eboard.control.Application;
import eboard.itf.model.IResponse;
import eboard.viewcontrolller.TestFrameController;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.DefaultListModel;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.text.DefaultStyledDocument;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TestFrame.java
 *
 * Created on 2010-10-21, 15:57:40
 */

/**
 *
 * @author elf
 */
public class TestFrame extends javax.swing.JFrame {
    Application ap = null;
    DefaultListModel  model = new DefaultListModel ();
    /** Creates new form TestFrame */
    TestFrame() {
        initComponents();
        //this.tfc = new TestFrameController(this);
        System.out.println("testfrmae");
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaSend = new javax.swing.JTextArea();
        btSend = new javax.swing.JButton();
        cbxToWho = new ColorfulComboBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaReceive = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstUser = new ColorfulList();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane1 = new ColorfulTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtaSend.setColumns(20);
        jtaSend.setRows(5);
        jScrollPane1.setViewportView(jtaSend);

        btSend.setText("send");
        btSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSendActionPerformed(evt);
            }
        });

        jLabel1.setText("to:");

        jtaReceive.setColumns(20);
        jtaReceive.setRows(5);
        jScrollPane2.setViewportView(jtaReceive);

        jScrollPane3.setViewportView(lstUser);

        jScrollPane4.setViewportView(jTextPane1);

        jMenu1.setText("File");

        jMenuItem2.setText("quit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("New");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("close");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("exit");
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Connect");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxToWho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addComponent(btSend)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxToWho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSend)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSendActionPerformed
//        IResponse r =
//            ap.sendMsg2All("192.168.137.13010test room", "test msg to all");
//        System.out.println(r.isSuccess());
//        System.out.println(r.getResponseMsg());

         
//    JList list = new JList(model);


    // Initialize the list with items

        
//    ListCellRenderer renderer = new ColorfulListCellRenderer();
//    this.lstUser.setCellRenderer(renderer);



//    for (int i = 0; i < items.length; i++) {
      //model.add(i, items[i]);
      ((ColorfulList)lstUser).addElement(new ColorfulCell("1","2",new Color((int)(Math.random()*255),(int)Math.random()*255,(int)(Math.random()*255))));
      ((ColorfulList)lstUser).addElement(new ColorfulCell("1","32",Color.blue));
//      ((ColorfulList)lstUser).setSelectedIndex(1);;
//    }

//     MutableAttributeSet attr = new SimpleAttributeSet();
//    StyleConstants.setForeground(attr, Color.red);
//    this.jTextPane1.setCharacterAttributes( attr, false);
//    this.jTextPane1.setText("123123");
//    StyleConstants.setForeground(attr, Color.blue);
//    this.jTextPane1.setCharacterAttributes( attr, false);
//    this.jTextPane1.setText("123123");
    DefaultStyledDocument d = new DefaultStyledDocument ();
    ((ColorfulTextPane)this.jTextPane1).append("123\n");
    ((ColorfulTextPane)this.jTextPane1).append("123\n",Color.yellow);
    ((ColorfulTextPane)this.jTextPane1).append("123\n");
    ((ColorfulTextPane)this.jTextPane1).append("123\n",Color.red);

    }//GEN-LAST:event_btSendActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        createRoom();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        ap = Application.getInstance();
        ap.init("test2", 3013);
        IResponse r =
        ap.enterRoom("192.168.137.1", 3010, "test", "");

        System.out.println(r.isSuccess());
        System.out.println(r.getResponseMsg());

        //javax.swing.JOptionPane.showInputDialog(this, "123213");
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        IResponse r =
        ap.redo("192.168.137.13010test");

        System.out.println(r.isSuccess());
        System.out.println(r.getResponseMsg());
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        IResponse r = 
        ap.undo("192.168.137.13010test");
        System.out.println(r.isSuccess());
        System.out.println(r.getResponseMsg());
        JPopupMenu m = new JPopupMenu();
        JMenuItem jmi = new JMenuItem("11");
        m.add(jmi);
//        lstUser.addMouseListener(new MouseListener(){
//
//        });
        jmi.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                System.out.println(e.getSource().toString());

            }
        });
        this.lstUser.add(m);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestFrame().setVisible(true);
            }
        });
    }

    
    public boolean receiveMsg(String msg){
        try{
            this.jtaReceive.setText(msg);
        }catch(Exception e){
            e.printStackTrace();
            return false;
        }
        return true;
    }

    public void sendMsg(String msg){
        try{
            this.jtaSend.setText(msg);
        }catch(Exception e){
            e.printStackTrace();
           
        }

    }

    void createRoom(){
        ap = Application.getInstance();
        ap.init("test1", 3010);
        IResponse r =
        ap.createRoom( "test room", "pwd");
        System.out.println(r.isSuccess());
        System.out.println(r.getResponseMsg());
        //this.tfc.createRoom("127.0.0.1", 2000, "test room", "pwd");
    }

//    private class ColorFulCell {
//        Color c = null;
//        String n = "";
//        String i = "";
//        ColorFulCell(String name, String id, Color color){
//            n = name;
//            i = id;
//            c = color;
//        }
//    }
//
//    private class ColorFulListCellRenderer implements ListCellRenderer {
//        protected DefaultListCellRenderer defaultRenderer = new DefaultListCellRenderer();
//
//      public Component getListCellRendererComponent(JList list, Object value,
//          int index, boolean isSelected, boolean cellHasFocus) {
//       // Font theFont = null;
//        Color theForeground = null;
////        Icon theIcon = null;
//        String theText = null;
//
//        JLabel renderer = (JLabel) defaultRenderer
//            .getListCellRendererComponent(list, value, index, isSelected,
//                cellHasFocus);
//
//        if (value instanceof ColorFulCell) {
//            ColorFulCell val = (ColorFulCell) value;
////          theFont = (Font) values[0];
//          theForeground = (Color) val.c;
////          theIcon = (Icon) values[2];
//          theText = (String) val.n;
//        } else {
////          theFont = list.getFont();
//          theForeground = list.getForeground();
//          theText = "";
//        }
//        if (!isSelected) {
//          renderer.setForeground(theForeground);
//        }
////        if (theIcon != null) {
////          renderer.setIcon(theIcon);
////        }
//        renderer.setText(theText);
////        renderer.setFont(theFont);
//        return renderer;
//      }


//    }
    private TestFrameController tfc = null;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSend;
    private javax.swing.JComboBox cbxToWho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextArea jtaReceive;
    private javax.swing.JTextArea jtaSend;
    private javax.swing.JList lstUser;
    // End of variables declaration//GEN-END:variables

}


